### ISSUE TITLE
Bug: Name Resets

### ISSUE THREAD

**Issue by DracoClaw** [12944qwerty/css-toggler#2] opened 2021-11-04 23:43 UTC
When disabling and then enabling a snippet, the title resets.

**Comment by GriefMoDz** [comment] 2021-11-12 00:56
As was previously discussed in the Powercord server, unfortunately both "I Won The Game" and I were unable to find a way to reproduce this bug. Due to this, we've decided that we'll be closing this issue. Please feel free to leave a comment on here again if you happen to continue experiencing this problem. Thank you.

**Closed as completed by GriefMoDz** 2021-11-12 00:56 UTC
Labels: bug, wontfix
